[tool.poetry]
name = "freight-trust-staking-backend"
version = "0.1.0"
description = "backend for staking dapp"
authors = ["sam <sam@freighttrust.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
